# Temporary pipeline with VM image

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: curl -o- -L https://yarnpkg.com/install.sh | bash
  displayName: 'Install yarn'

- script: yarn
  displayName: 'Install dependencies'

- script: yarn build
  displayName: 'Run webpack'

- task: AWSCLI@1
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  inputs:
    awsCredentials: 'azure-pipelines-pcr'
    regionName: 'us-east-1'
    awsCommand: 's3'
    awsSubCommand: 'sync'
    awsArguments: 'dist/ s3://pcr.tirr.dev/questsim/ --delete --acl public-read'
  displayName: 'Deploy to S3'